import { VersionName } from "@types"

const folder = "/games-images/"

export const gameImageUrlPerVersionName = new Map<VersionName, string>([
    ["Red", folder + "red.png"],
    ["Blue", folder + "blue.png"],
    ["Yellow", folder + "yellow.png"],
    ["Gold", folder + "gold.png"],
    ["Silver", folder + "silver.png"],
    ["Crystal", folder + "crystal.png"],
    ["Ruby", folder + "ruby.png"],
    ["Sapphire", folder + "sapphire.png"],
    ["Emerald", folder + "emerald.png"],
    ["Fire Red", folder + "fire-red.png"],
    ["Leaf Green", folder + "leaf-green.png"],
    ["Diamond", folder + "diamond.png"],
    ["Pearl", folder + "pearl.png"],
    ["Platinum", folder + "platinum.png"],
    ["Heart Gold", folder + "heart-gold.png"],
    ["Soul Silver", folder + "soul-silver.png"],
    ["Black", folder + "black.png"],
    ["White", folder + "white.png"],
    ["Colosseum", folder + "colosseum.png"],
    ["XD", folder + "xd.png"],
    ["Black 2", folder + "black-2.png"],
    ["White 2", folder + "white-2.png"],
    ["X", folder + "x.png"],
    ["Y", folder + "y.png"],
    ["Omega Ruby", folder + "omega-ruby.png"],
    ["Alpha Sapphire", folder + "alpha-sapphire.png"],
    ["Sun", folder + "sun.png"],
    ["Moon", folder + "moon.png"],
    ["Ultra Sun", folder + "ultra-sun.png"],
    ["Ultra Moon", folder + "ultra-moon.png"],
    ["Let's Go Pikachu", folder + "lets-go-pikachu.png"],
    ["Let's Go Eevee", folder + "lets-go-eevee.png"],
    ["Sword", folder + "sword.png"],
    ["Shield", folder + "shield.png"],
    ["The Isle Of Armor", folder + "the-isle-of-armor.png"],
    ["The Crown Tundra", folder + "the-crown-tundra.png"],
    ["Brilliant Diamond", folder + "brilliant-diamond.png"],
    ["Shining Pearl", folder + "shining-pearl.png"],
    ["Legends Arceus", folder + "legends-arceus.png"],
    ["Scarlet", folder + "scarlet.png"],
    ["Violet", folder + "violet.png"],
    ["The Teal Mask", folder + "the-teal-mask.png"],
    ["The Indigo Disk", folder + "the-indigo-disk.png"]
])
